version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pip install aws-sam-cli
      - sam --version
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
Cancel update build specification
Build specification
Use the buildspec.yml in the source code root directory
Insert build commands
Buildspec name
Type your buildspec name
Certificate
If you have a self-signed certificate or a certificate signed by a certification authority, choose the option to install it from your S3 bucket.
Do not install any certificate
Install certificate from your S3
Artifacts: Where to put the artifacts from this build project
Type*

Cache
Type*

Service role
Specify a service role that enables AWS CodeBuild to call dependent AWS services on your behalf. Learn more.

Create a role
