version: 0.2

phases:
  install:
    commands: 
      - export PR_UNIQUE_CODE=`echo FP-$CODEBUILD_SOURCE_VERSION | sed 's/\///'`
      - printenv
  build:
    commands:      
      - aws clouformation package --template-file template.yaml --s3-bucket grimlocks-testing --output-template-file packaged.yaml
      - aws cloudformation deploy --template-file packaged.yaml --stack-name $PR_UNIQUE_CODE --capabilities CAPABILITY_IAM
