version: 0.2

env:
  variables:
     FP_PR_BRANCH_NAME: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "valuasdasdsde"

phases:
  install:
    commands: 
      - git branch
  #pre_build:
    #commands:
      #- sh scripts/envvars.sh    
  #build:
    #commands:
      #- sh scripts/envvars.sh
      #- printenv
      #- aws cloudformation package --template-file template.yaml --s3-bucket grimlocks-testing --output-template-file packaged.yaml
      # - run tests here 
      #- aws cloudformation deploy --template-file packaged.yaml --stack-name fp-$CODEBUILD_SOURCE_VERSION --capabilities CAPABILITY_IAM
  #post_build:
    #commands:
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
