
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple example of Lambda Deployments with SAM.
Resources:
  LambdaFunctionOne:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/lambda1/index.handler
      Runtime: nodejs8.11
      CodeUri: services/lambda1/
      Events:
        GetFunctionOne:
          Type: Api
          Properties:
            Path: /resource/
            Method: get

Outputs:
  ApiURL:
    Description: "API endpoint URL for X environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resource/"

