
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple example of Lambda Deployments with SAM.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Role: !GetAtt AWSLambdaExecute.Arn
    Properties:
      Role: arn:aws:iam::330019646059:role/fp-lambda-basic
      CodeUri: services/hello_world/
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn


